name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install rst2pdf
        run: |
          pip install rst2pdf
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme
          pip install idna==2.10
          pip install sphinxcontrib-jquery==2.0.0
          pip install urllib3==1.25.11
      - name: PDF build
        run: |
          sphinx-build -b pdf docs/source _build
      - name: Sphinx build
        run: |
          sphinx-build docs/source _build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
